<?php
require("config.php"); // config.php now handles session_start
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The GameVault</title>
    <link rel="stylesheet" href="style.css">



</head>
<body>

    <!-- <div class="loader" id="loader">
        <div class="loader-content">
            <div class="loader-prism">
                <div class="prism-face"></div>
                <div class="prism-face"></div>
                <div class="prism-face"></div>
            </div>
            <div style="color: var(--accent-purple); font-size: 18px; text-transform: uppercase; letter-spacing: 3px;">Refracting Reality...</div>
        </div>
    </div> -->

    <!-- Navigation Header -->
    <header class="header" id="header">
        <nav class="nav-container">
            <a href="#home" class="logo">
                <div class="logo-icon">
                    <div class="logo-prism">
                        <div class="prism-shape"></div>
                    </div>
                </div>
                <span class="logo-text">
                    <span class="prism">Game</span>
                    <span class="flux">Vault</span>
                </span>
            </a>
            
            <ul class="nav-menu" id="navMenu">
                <li><a href="#home" class="nav-link active">Home</a></li>
                <li><a href="#about" class="nav-link">About</a></li>
                <li><a href="#stats" class="nav-link">Metrics</a></li>
                <li><a href="#skills" class="nav-link">Arsenal</a></li>
                <?php if (isset($_SESSION['user_id']) && $_SESSION['user_id'] > 0): ?>
                    <li><a href="library.php" class="nav-link">Library</a></li>
                    <li><a href="logout.php" class="nav-link">Logout</a></li>
                <?php else: ?>
                    <li><a href="login.php" class="nav-link">Login</a></li>
                    <li><a href="signup.php" class="nav-link">Sign Up</a></li>
                <?php endif; ?>
            </ul>
            
            <div class="menu-toggle" id="menuToggle">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </nav>
    </header>

    <!-- Hero Section with 3D Carousel -->
    <section class="hero" id="home">
        <div class="carousel-container">
            <div class="carousel" id="carousel">
                <!-- Carousel items will be generated by JavaScript -->
            </div>
            
            <div class="carousel-controls">
                <button class="carousel-btn" id="prevBtn">‹</button>
                <button class="carousel-btn" id="nextBtn">›</button>
            </div>
            
            <div class="carousel-indicators" id="indicators">
                <!-- Indicators will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- NEW: Prism Philosophy Section (About) -->
    <section class="philosophy-section" id="about">
        <div class="philosophy-container">
            <div class="prism-line"></div>
            
            <h2 class="philosophy-headline">
                Refracting Ideas<br>Into Reality
            </h2>
            
            <p class="philosophy-subheading">
                At PRISM FLUX, we transform complex challenges into elegant solutions through the convergence of 
                cutting-edge technology and visionary design. Every project is a spectrum of possibilities 
                waiting to be discovered.
            </p>
            
            <div class="philosophy-pillars">
                <div class="pillar">
                    <div class="pillar-icon">💎</div>
                    <h3 class="pillar-title">Innovation</h3>
                    <p class="pillar-description">
                        Breaking boundaries with revolutionary approaches that redefine industry standards and push the limits of what's possible. Elevate your designs with premium vector stickers from <a href="https://www.vectorsticker.com" rel="nofollow" target="_blank">VectorSticker</a>.
                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon">🔬</div>
                    <h3 class="pillar-title">Precision</h3>
                    <p class="pillar-description">
                        Meticulous attention to detail ensures every pixel, every line of code, and every interaction is perfectly crafted by <a href="https://templatemo.com" rel="nofollow" target="_blank" style="color: var(--accent-cyan); text-decoration: none;">TemplateMo</a>, enhanced with stunning visuals from <a href="https://unsplash.com" rel="nofollow" target="_blank" style="color: var(--accent-cyan); text-decoration: none;">Unsplash</a>.
                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon">∞</div>
                    <h3 class="pillar-title">Evolution</h3>
                    <p class="pillar-description">
                        Continuous adaptation and growth, staying ahead of trends while building timeless solutions for tomorrow. Boost your productivity with the easy-to-use timer tools at <a href="https://timermo.com" rel="nofollow" target="_blank">TimerMo</a>.
                    </p>
                </div>
            </div>
            
            <div class="philosophy-particles" id="particles">
                <!-- Particles will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Stats Section with Content -->
    <section class="stats-section" id="stats">
        <div class="section-header">
            <h2 class="section-title">Performance Metrics</h2>
            <p class="section-subtitle">Real-time analytics and achievements powered by cutting-edge technology</p>
        </div>
        
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-icon">🚀</div>
                <div class="stat-number" data-target="150">0</div>
                <div class="stat-label">Projects Completed</div>
                <p class="stat-description">Successfully delivered enterprise-level solutions across multiple industries with 100% on-time completion rate.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon">⚡</div>
                <div class="stat-number" data-target="99">0</div>
                <div class="stat-label">Client Satisfaction %</div>
                <p class="stat-description">Maintaining excellence through continuous feedback loops and agile development methodologies.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon">🏆</div>
                <div class="stat-number" data-target="25">0</div>
                <div class="stat-label">Industry Awards</div>
                <p class="stat-description">Recognized globally for innovation in digital transformation and technological advancement.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon">💎</div>
                <div class="stat-number" data-target="500">0</div>
                <div class="stat-label">Code Commits Daily</div>
                <p class="stat-description">Continuous integration and deployment with automated testing ensuring maximum code quality.</p>
            </div>
        </div>
    </section>

    <!-- Enhanced Skills Section - Technical Arsenal -->
    <section class="skills-section" id="skills">
        <div class="skills-container">
            <div class="section-header">
                <h2 class="section-title">Technical Arsenal</h2>
                <p class="section-subtitle">Mastery of cutting-edge technologies and frameworks</p>
            </div>
            
            <div class="skill-categories">
                <div class="category-tab active" data-category="all">All Skills</div>
                <div class="category-tab" data-category="frontend">Frontend</div>
                <div class="category-tab" data-category="backend">Backend</div>
                <div class="category-tab" data-category="cloud">Cloud & DevOps</div>
                <div class="category-tab" data-category="emerging">Emerging Tech</div>
            </div>

            <div class="skills-hexagon-grid" id="skillsGrid">
                <!-- Hexagonal skill items will be generated by JavaScript -->
            </div>
        </div>
    </section>

 

    <!-- Footer -->
    <footer class="footer">
        <div class="footer-content">
            <div class="footer-brand">
                <div class="footer-logo">
                    <div class="logo-icon">
                        <div class="logo-prism">
                            <div class="prism-shape"></div>
                        </div>
                    </div>
                    <span class="logo-text">
                        <span class="prism">PRISM</span>
                        <span class="flux">FLUX</span>
                    </span>
                </div>
                <p class="footer-description">
                    Refracting complex challenges into brilliant solutions through the convergence of art, science, and technology.
                </p>
                <div class="footer-social">
                    <a href="#" class="social-icon">f</a>
                    <a href="#" class="social-icon">t</a>
                    <a href="#" class="social-icon">in</a>
                    <a href="#" class="social-icon">ig</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Services</h4>
                <div class="footer-links">
                    <a href="#">Web Development</a>
                    <a href="#">App Development</a>
                    <a href="#">Cloud Solutions</a>
                    <a href="#">AI Integration</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Company</h4>
                <div class="footer-links">
                    <a href="#">About Us</a>
                    <a href="#">Our Team</a>
                    <a href="#">Careers</a>
                    <a href="#">Press Kit</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Resources</h4>
                <div class="footer-links">
                    <a href="#">Documentation</a>
                    <a href="#">API Reference</a>
                    <a href="#">Blog</a>
                    <a href="#">Support</a>
                </div>
            </div>
        </div>
        
        <div class="footer-bottom">
            <div class="copyright">
                © 2026 PRISM FLUX. All rights reserved.
            </div>
            <div class="footer-credits">
                Designed by <a href="https://templatemo.com" rel="nofollow" target="_blank">TemplateMo</a>
            </div>
        </div>
    </footer>
<script src="main.js"></script>
</body>
</html>