<?php
require("config.php"); // config.php now handles session_start
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The GameVault</title>
    <link rel="stylesheet" href="style.css">



</head>
<body>

    <!-- <div class="loader" id="loader">
        <div class="loader-content">
            <div class="loader-prism">
                <div class="prism-face"></div>
                <div class="prism-face"></div>
                <div class="prism-face"></div>
            </div>
            <div style="color: var(--accent-purple); font-size: 18px; text-transform: uppercase; letter-spacing: 3px;">Refracting Reality...</div>
        </div>
    </div> -->

    <!-- Navigation Header -->
    <header class="header" id="header">
        <nav class="nav-container">
            <a href="#home" class="logo">
                <div class="logo-icon">
                    <div class="logo-prism">
                        <div class="prism-shape"></div>
                    </div>
                </div>
                <span class="logo-text">
                    <span class="prism">Game</span>
                    <span class="flux">Vault</span>
                </span>
            </a>
            
            <ul class="nav-menu" id="navMenu">
                <li><a href="#home" class="nav-link active">Home</a></li>
                <li><a href="#about" class="nav-link">About</a></li>
                <li><a href="#stats" class="nav-link">Metrics</a></li>
                <li><a href="#skills" class="nav-link">Arsenal</a></li>
                <?php if (isset($_SESSION['user_id']) && $_SESSION['user_id'] > 0): ?>
                    <li><a href="library.php" class="nav-link">Library</a></li>
                    <li><a href="logout.php" class="nav-link">Logout</a></li>
                <?php else: ?>
                    <li><a href="login.php" class="nav-link">Login</a></li>
                    <li><a href="signup.php" class="nav-link">Sign Up</a></li>
                <?php endif; ?>
                <li><a href="admin_login.php" class="nav-link" style="color: var(--accent-cyan);">Admin</a></li>
            </ul>
            
            <div class="menu-toggle" id="menuToggle">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </nav>
    </header>

    <!-- Hero Section with 3D Carousel -->
    <section class="hero" id="home">
        <div class="carousel-container">
            <div class="carousel" id="carousel">
                <!-- Carousel items will be generated by JavaScript -->
            </div>
            
            <div class="carousel-controls">
                <button class="carousel-btn" id="prevBtn">‹</button>
                <button class="carousel-btn" id="nextBtn">›</button>
            </div>
            
            <div class="carousel-indicators" id="indicators">
                <!-- Indicators will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- NEW: Prism Philosophy Section (About) -->
    <section class="philosophy-section" id="about">
        <div class="philosophy-container">
            <div class="prism-line"></div>
            
            <h2 class="philosophy-headline">
                Refracting Ideas<br>Into Reality
            </h2>
            
            <p class="philosophy-subheading">
                Welcome to GameVault, where classic arcade games meet modern web technology. Dive into a curated 
                collection of timeless favorites and discover new challenges. Every game is a new adventure 
                waiting to be explored.
            </p>
            
            <div class="philosophy-pillars">
                <div class="pillar">
                    <div class="pillar-icon">🎮</div>
                    <h3 class="pillar-title">Classic Games</h3>
                    <p class="pillar-description">
                        Experience the nostalgia of timeless arcade classics. From Pac-Man to Snake, Minesweeper to 
                        Sudoku, we've gathered the best retro games that defined generations of gaming.
                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon">⚡</div>
                    <h3 class="pillar-title">Instant Play</h3>
                    <p class="pillar-description">
                        No downloads, no installations. Jump straight into action with our browser-based games. 
                        All games are optimized for smooth performance and responsive gameplay across all devices.
                    </p>
                </div>
                
                <div class="pillar">
                    <div class="pillar-icon">🏆</div>
                    <h3 class="pillar-title">Your Library</h3>
                    <p class="pillar-description">
                        Create your personal game library, track your progress, and save your achievements. 
                        Build your gaming profile and compete with friends in your favorite games.
                    </p>
                </div>
            </div>
            
            <div class="philosophy-particles" id="particles">
                <!-- Particles will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <!-- Stats Section with Content -->
    <section class="stats-section" id="stats">
        <div class="section-header">
            <h2 class="section-title">Performance Metrics</h2>
            <p class="section-subtitle">Track your gaming journey with real-time statistics and achievements. See how you stack up against players worldwide and celebrate your milestones as you master each game.</p>
        </div>
        
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-icon">🎮</div>
                <div class="stat-number" data-target="6">0</div>
                <div class="stat-label">Games Available</div>
                <p class="stat-description">A curated collection of classic arcade games including Pac-Man, Snake, Minesweeper, Sudoku, Tic-Tac-Toe, and Breakout. More games are being added regularly to expand your gaming library.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon">⚡</div>
                <div class="stat-number" data-target="10000">0</div>
                <div class="stat-label">Games Played</div>
                <p class="stat-description">Join thousands of players who have enjoyed hours of entertainment across our platform. Every game session contributes to our growing community of gaming enthusiasts.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon">🏆</div>
                <div class="stat-number" data-target="5000">0</div>
                <div class="stat-label">High Scores Set</div>
                <p class="stat-description">Players have achieved incredible milestones and set impressive records. Challenge yourself to beat the top scores and claim your spot on the leaderboard.</p>
            </div>
            
            <div class="stat-card">
                <div class="stat-icon">👥</div>
                <div class="stat-number" data-target="2500">0</div>
                <div class="stat-label">Active Players</div>
                <p class="stat-description">A thriving community of gamers who return daily to play their favorites and discover new challenges. Connect with fellow players and share your achievements.</p>
            </div>
        </div>
    </section>

    <!-- Enhanced Skills Section - Game Collection -->
    <section class="skills-section" id="skills">
        <div class="skills-container">
            <div class="section-header">
                <h2 class="section-title">Game Collection</h2>
                <p class="section-subtitle">Explore our curated selection of classic arcade games. Each game offers unique challenges and endless entertainment.</p>
            </div>
            
            <div class="skill-categories">
                <div class="category-tab active" data-category="all">All Games</div>
                <div class="category-tab" data-category="arcade">Arcade</div>
                <div class="category-tab" data-category="puzzle">Puzzle</div>
                <div class="category-tab" data-category="strategy">Strategy</div>
            </div>

            <div class="skills-hexagon-grid" id="skillsGrid">
                <!-- Hexagonal game items will be generated by JavaScript -->
            </div>
        </div>
    </section>

 

    <!-- Footer -->
    <footer class="footer">
        <div class="footer-content">
            <div class="footer-brand">
                <div class="footer-logo">
                    <div class="logo-icon">
                        <div class="logo-prism">
                            <div class="prism-shape"></div>
                        </div>
                    </div>
                    <span class="logo-text">
                        <span class="prism">Game</span>
                        <span class="flux">Vault</span>
                    </span>
                </div>
                <p class="footer-description">
                    Your ultimate destination for classic arcade games. Play, compete, and relive the golden age of gaming with our curated collection of timeless favorites.
                </p>
                <div class="footer-social">
                    <a href="#" class="social-icon">f</a>
                    <a href="#" class="social-icon">t</a>
                    <a href="#" class="social-icon">in</a>
                    <a href="#" class="social-icon">ig</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Games</h4>
                <div class="footer-links">
                    <a href="#skills">All Games</a>
                    <a href="#skills">Arcade Games</a>
                    <a href="#skills">Puzzle Games</a>
                    <a href="#skills">Strategy Games</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Account</h4>
                <div class="footer-links">
                    <a href="login.php">Login</a>
                    <a href="signup.php">Sign Up</a>
                    <a href="library.php">My Library</a>
                    <a href="#about">About</a>
                </div>
            </div>
            
            <div class="footer-section">
                <h4>Support</h4>
                <div class="footer-links">
                    <a href="#stats">Leaderboards</a>
                    <a href="submit_game_request.php">Request Game</a>
                    <a href="#about">How to Play</a>
                    <a href="#">Contact</a>
                </div>
            </div>
        </div>
        
        <div class="footer-bottom">
            <div class="copyright">
                © 2026 GameVault. All rights reserved.
            </div>
            <div class="footer-credits">
                Designed by Our Team
            </div>
        </div>
    </footer>
<script src="main.js"></script>
</body>
</html>